### ISSUE TITLE
Numeric Annotation Glyphs aren't correctly removed

### ISSUE THREAD

**Issue by kenneth-venken** [amyboyd/pgn-parser#1]
In the first game of 200open.pgn we have: **29... Bc4 $1 $19 30. Nf6 e2**
Although $1 is correctly removed from the moves string, $19 will become 9 and this breaks the moves.

Current code in private function addMoves of PgnParser only checks for 1 digit:
`$line = preg_replace('/\$[0-9]/', '', $line);`

it should be changed to:
`$line = preg_replace('/\$[0-9]+/', '', $line);`

**Comment by amyboyd** [comment]
Thanks for reporting this. If someone makes a pull request, I'll be happy to merge.
